WIP init module config
CGI-OPEN-ENT-NG/minibadge pull request #1
Opened 2022-07-28 15:36 UTC by qpic-cgi

2022-07-29 10:06 UTC, alicedraillard approved these changes

2022-07-29 10:09 UTC, JinDouang requested changes

2022-07-29 10:09 UTC, JinDouang commented on README.md
>  [Documentation technique](./docs/README.md)
Tu comptes créer un dossier avec la doc technique etc...?

2022-07-29 10:09 UTC, JinDouang commented on src/main/resources/public/ts/controllers/minibadge.controller.ts
> +export const minibadgeController = ng.controller('MinibadgeController', ['$scope', 'route', function ($scope, route) {
Comme ce module sera potentiellement refait en react il faudra l'adapter en classe (en prenant exemple d'angular 13+)

2022-07-29 10:09 UTC, JinDouang commented on jest.config.js
> +        "<rootDir>/module-starting-pack/build/",
à renommer!

2022-07-29 10:52 UTC, qpic-cgi commented on README.md
>  [Documentation technique](./docs/README.md)
non je pense pas, ce sera une redirection vers le confluence à la limite

2022-07-29 10:53 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/minibadge.controller.ts
> +export const minibadgeController = ng.controller('MinibadgeController', ['$scope', 'route', function ($scope, route) {
yes, ça va bouger de toute manière, pour le moment, c'est juste histoire de dire que ça affiche un truc

2022-07-29 12:52 UTC, JinDouang approved these changes

2022-07-29 12:56 UTC, merged

2022-08-02 07:33 UTC, sjollois commented on gradle.properties
> +modowner=fr.cgi
Pourquoi c'est fr.cgi et pas fr.openent ?

2022-08-02 07:36 UTC, qpic-cgi commented on gradle.properties
> +modowner=fr.cgi
parce-que jusqu'à maintenant, on m'a pas fait de commentaire pour que ce soit fr.cgi :p

2022-08-02 07:37 UTC, qpic-cgi commented on gradle.properties
> +modowner=fr.cgi
donc je ne sais pas 😅