fix(BadgeList):#MBA-41:fix css more spaces between elems
CGI-OPEN-ENT-NG/minibadge pull request #10
Opened 2022-10-12 12:10 UTC by Rseuret

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-12 12:17 UTC, JinDouang requested changes

2022-10-12 12:17 UTC, JinDouang commented on src/main/resources/public/sass/global/components/_badge.scss
> +      margin-left:0.2%;
que représente ces valeurs 0.2/0.3% ?
On peut pas utiliser les multiples de 8 ? genre 8px 16 px etc...

2022-10-12 12:17 UTC, JinDouang commented on src/main/resources/public/sass/global/components/_card.scss
> +              padding-left: 2.5px;
pourquoi 2.5px ? Pas possible d'avoir un multiple de 8 ?

2022-10-12 12:20 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-list/badge-list.html
> +            <i18n>
En réalité, la balise i18n n'est pas nécessaire du coup.

2022-10-17 08:40 UTC, qpic-cgi commented on src/main/resources/public/sass/global/_mixins.scss
> +}
pas idiot ! 👍🏻

2022-10-17 09:59 UTC, sjollois approved these changes

2022-10-18 08:08 UTC, merged