feat(chart): #MBA-11 #MBA-12 implement chart to accept Minibadge module
CGI-OPEN-ENT-NG/minibadge pull request #13
Opened 2022-10-14 14:15 UTC by qpic-cgi

## Describe your changes

Ajout d'une modal permettant d'accepter la Charte du module.
Si la chart est accepté, 2 actions vont lui être attribués s'ils possède le droit correspondant:
- l'utilisateur à le droit d'assigner un badge => en acceptant la charte, il peut assigner des badges
- l'utilisateur à le droit de recevoir un badge => en acceptant la charte, il peut recevoir des badges

Des droits sur les endpoints ! enfin !

## Checklist tests
- Aller sur un utilisateur qui n'a pas encore accepter la chart (mais qui a quand même le droit accept et/ou receive)
- Sur la page d'accueil, la charte s'ouvre (seulement si elle n'a pas été acceptée)
- accepter la charte
- tester l'assignation et la réception de badge en fonction
- Bonus: A l'assignation, la recherche n'affiche que les utilisateurs ayant le droit de recevoir un badge.

## Issue ticket number and link
[Jira - MBA-11](https://jira.support-ent.fr/browse/MBA-11)
[Jira - MBA-12](https://jira.support-ent.fr/browse/MBA-12)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-14 14:24 UTC, qpic-cgi commented on src/main/resources/public/sass/global/generics/_switch.scss
> +switch {
récupération de CDT

2022-10-14 14:29 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +    private Future<JsonObject> getUserCachedPermissions(final HttpServerRequest request) {
Traitement récupéré d'ODE
https://github.com/opendigitaleducation/entcore/blob/1028bbcd38c4fd5f02ac9e628ec5f71c97bfe52c/directory/src/main/java/org/entcore/directory/controllers/UserBookController.java#L646

2022-10-17 08:39 UTC, flmartineau commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +                                    String.format("[Minibadge@%s::refreshPreferences] User is not allowed to assign.",
[Minibadge@%s::authorize]

2022-10-17 08:40 UTC, flmartineau commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +                            String.format("[Minibadge@%s::refreshPreferences] Fail to store permissions preferences " +
[Minibadge@%s::getAndCachePermissionsPreferences]

2022-10-17 09:25 UTC, flmartineau commented on src/main/resources/public/ts/directives/chart/chart.html
> +                <span><i18n>J'accepte de recevoir des badges</i18n></span>&nbsp;
i18n ?

2022-10-17 09:56 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/chart/chart.html
> +                <span><i18n>J'accepte de recevoir des badges</i18n></span>&nbsp;
héhé 😝

2022-10-18 08:56 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/FakeRight.java
> +public class FakeRight extends ControllerHelper {
elle sert à quoi cette classe je ne comprends pas ? ça fait beaucoup de code pour juste init les droits non ?

2022-10-18 08:56 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/UserController.java
> +    @ResourceFilter(AssignRight.class)
Ce n'est pas trop gourmand en ressources ici ?

2022-10-18 08:56 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +        String query = String.format("MATCH (u:User {id:{userId}})-[:PREFERS]->(uac:UserAppConf) " +
pk tu ne l'as pas mis dans le neo4jHelper ?

2022-10-18 08:56 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +public class UsersAssignRight implements ResourcesProvider {
On est comment en termes de perfs de cette classe de Sécurité ??

2022-10-18 09:27 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/FakeRight.java
> +public class FakeRight extends ControllerHelper {
C'est que je ne l'ai pas précisé, mais c'est un fonctionnement qui vient de présences:
https://github.com/OPEN-ENT-NG/presences/blob/dev/presences/src/main/java/fr/openent/presences/controller/FakeRight.java

Ca permet de générer les droits à un seul endroit, et ainsi s'assurer qu'il n'y ai pas de régénération de droits dupliqués (ça nous est arrivé plusieurs fois)
Ca permet aussi en plus de lister les différent droits disponibles.

2022-10-18 09:27 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/UserController.java
> +    @ResourceFilter(AssignRight.class)
Pas que je sache, pourquoi ça ?

2022-10-18 09:29 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +        String query = String.format("MATCH (u:User {id:{userId}})-[:PREFERS]->(uac:UserAppConf) " +
C'est un morceau de requête dont je vais avoir besoins à plusieurs endroits.

Politiquement, nous ne somme pas vraiment sensé utiliser de neo4j,
l'idée, c'est d'en écrire le moins possible, et de le rendre un maximum réutilisable.

2022-10-18 09:33 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +public class UsersAssignRight implements ResourcesProvider {
Ce sont des requêtes filtrantes sur un groupe d'utilisateur très restreint 
(le seul ennemi potentiel c'est qu'un jours, les utilisateurs puissent assigner des badges illimités aux utilisateurs, et qu'il s'amuses à en créer des 10aines de millier, à la mains, donc pas de soucis à ce faire de ce côté)
Et donc, ce n'est lourd du tout.

2022-10-18 09:54 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/UserController.java
> +    @ResourceFilter(AssignRight.class)
Car à chaque fois que l'utilisateur va rechercher un utilisateur, ça va vérifier s'il a les droits etc...
alors qu'il y a pas vraiment besoin de vérifs

2022-10-18 09:55 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +public class UsersAssignRight implements ResourcesProvider {
tu es sur que tout ces traitements ne sont pas lourds ?

2022-10-18 09:57 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/UserController.java
> +    @ResourceFilter(AssignRight.class)
le droit AssignRight fait, juste une petite vérif au niveau du droit assign (il n'y a pas de requête implémenté), ce n'est vraiment pas lourd du tout

2022-10-18 10:00 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +public class UsersAssignRight implements ResourcesProvider {
Certains à 100%, on peut le montrer à @JinDouang pour avoir un 2eme avis si tu veux,
c'est vraiment une requête Neo filtrant quelques utilisateurs,
la complexité du code est surtout du au fait qu'il y a pleins de petit contrôles, pour autant, en somme, c'est juste une vérification de quelque booléen !
Si je ne t'ai pas convaincu, on peu s'appeler pour discuter du code aussi 😄

2022-10-18 10:01 UTC, Sofianebernoussi commented on src/main/resources/i18n/fr.json
> +  "minibadge.chart.welcome": "Bienvenu dans le module Minibadges",
normal ces textes? (la langue) BienvenuE

2022-10-18 10:01 UTC, Sofianebernoussi commented on src/main/resources/public/sass/global/components/_icon.scss
> +    font-family: 'material-icons';
change le font family pour eviter pb future de version (cf : https://github.com/OPEN-ENT-NG/form/pull/113)

2022-10-18 10:05 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +        String query = String.format("MATCH (u:User {id:{userId}})-[:PREFERS]->(uac:UserAppConf) " +
HA ! j'ai juste très mal interprété ta question.

La raison pour laquelle je l'ai directement fait dans le Resource Provider, c'est qu'il sont instancier à l'initialisation du module. Il ne peuvent donc pas récupérer les instances suivantes.
J'ai donc pour reflexe (comme c'est fait dans les modules d'ODE) d'écrire en brut mes requêtes.

Pour autant, ce serrais faire un appel de méthode static, et je ne sais pas comment java gère les l'instanciations des méthodes static, donc il est très vrai que ça peux fonctionner !

J'essaie ça si tu veux, et je te dis 😉

2022-10-18 10:11 UTC, qpic-cgi commented on src/main/resources/i18n/fr.json
> +  "minibadge.chart.welcome": "Bienvenu dans le module Minibadges",
haha, je copie colle, ce qui vient des maquettes 😄

2022-10-18 10:11 UTC, qpic-cgi commented on src/main/resources/public/sass/global/components/_icon.scss
> +    font-family: 'material-icons';
je ne l'ai pas rappeler dans ce ticket,
mais j'ai un ticket prévu pour ça, car on a beaucoup d'icones à changer, et ça va prendre un certain temps du coup

2022-10-18 10:13 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/UserController.java
> +    @ResourceFilter(AssignRight.class)
ah oui je confond avec UsersAssignRight, escuce moi

2022-10-18 10:15 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +        String query = String.format("MATCH (u:User {id:{userId}})-[:PREFERS]->(uac:UserAppConf) " +
Ah oui c'est pour ça, non mais c'est bon on peut laisser comme ça

2022-10-18 10:22 UTC, sjollois approved these changes

2022-10-18 10:22 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +    private Future<JsonArray> getUsers(HttpServerRequest request, List<String> ownerIds) {
Tu peux redescendre cette fonction dans le fichier pour respecter le même ordre des fonctions que dans authorize

2022-10-18 10:22 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +public class UsersAssignRight implements ResourcesProvider {
Oui c'est vrai qu'il est bien complexe, mais bravo tu t'en ai sorti 👍 
C'est bon pour moi au final, après deuxième lecture

2022-10-18 12:00 UTC, JinDouang requested changes

2022-10-18 12:00 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/core/constants/Rights.java
> +    public static final String FULLNAME_RECEIVE = "fr.cgi.minibadge.controller.FakeRight|receive";
Pour être sur du package (si jamais ça doit changer) tu pourrais faire ça 

```suggestion
 public static final String FULLNAME_RECEIVE = String.format("%s.%s|assign", FakeRight.class.getPackage().getName(), FakeRight.class.getSimpleName());
```

Ca t'éviterait de devoir changer le Rights si jamais ca change de package/controller (même si c'est très peu probable mais si on peut éviter d'écrire en magic string "fr.cgi.minibadge.controller" comme on a déjà l'info avec le model Package/Class)

2022-10-18 12:00 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/helper/WorkflowHelper.java
> +        return false;
```suggestion
        return actions.stream().anyMatch(a -> action.equals(a.getDisplayName()));
```

2022-10-18 12:00 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +                    .compose(permissions -> getUserPermissions(permissions, userInfos, request))
```suggestion
                    .compose(cachedPermissions -> getUserPermissions(cachedPermissions , userInfos, request))
```

2022-10-18 12:36 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java
> +                    .compose(permissions -> getUserPermissions(permissions, userInfos, request))
yes, c'est exactement ce que j'ai fait ^^

2022-10-18 12:38 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/helper/WorkflowHelper.java
> +        return false;
bha carrément, pour une fois que je ne le vois pas 😝

2022-10-18 12:40 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/core/constants/Rights.java
> +    public static final String FULLNAME_RECEIVE = "fr.cgi.minibadge.controller.FakeRight|receive";
Yes ! j'aime beaucoup ! je prend 😉

2022-10-18 13:09 UTC, JinDouang approved these changes

2022-10-18 13:14 UTC, merged