fix(Badges)MBA-43:fix search query -> now open refused badges
CGI-OPEN-ENT-NG/minibadge pull request #14
Opened 2022-10-17 06:36 UTC by Rseuret

## Describe your changes
open refused badges if elems match search
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MBA-43
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-17 08:00 UTC, BastienBenard commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +          this.isOpenedOption =  (this.$scope.vm.isOpenedOption !== undefined) ? this.$scope.vm.isOpenedOption : false;
Est ce que tu ne peux pas faire directement `this.isOpenedOption = !!this.$scope.vm.isOpenedOption` ?

2022-10-17 08:12 UTC, qpic-cgi requested changes

2022-10-17 08:12 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/minibadge.controller.ts
> +                this.isOpenedOption = this.payload.query && this.payload.query.length && this.payload.query.length > 0;
this.payload.query && !!this.payload.query.trim().length
c'est suffisant

2022-10-17 08:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +            this.isOpenedOption = newOption;
pas nécessaire avec un 2 way binding => 
scope : {
...
"paramètre": "="
...
}

2022-10-17 08:42 UTC, sjollois requested changes

2022-10-17 08:42 UTC, sjollois commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +            this.isOpenedOption = !!this.$scope.vm.isOpenedOption
indentation

2022-10-17 13:35 UTC, JinDouang approved these changes

2022-10-18 08:36 UTC, sjollois approved these changes

2022-10-18 09:38 UTC, qpic-cgi requested changes

2022-10-18 09:38 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +    isOpenedOption:boolean;
Je vais faire le tatillon, et je le fais avant que ce soit quelqu'un d'autre qui le fasse 😛 
donc un petit coup de ALT + MAJ + L pour les espaces serais le bienvenu 😄

2022-10-18 09:38 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +        this.isOpenedOption = !!this.$scope.vm.isOpenedOption
;

2022-10-18 09:38 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/minibadge.controller.ts
> +                this.isOpenedOption = this.payload.query && !!this.payload.query.trim().length
;

2022-10-18 14:24 UTC, qperie approved these changes

2022-10-18 14:25 UTC, qperie commented on src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts
> +    isOpenedOption:boolean;
Je vais tatillonner aussi : @qpic-cgi on a pas tous les mêmes raccourcis donc ALT+MAJ+L marche pas forcément pour Rémy x)

2022-10-21 12:38 UTC, merged