feat(User) #MBA-44: add table user and link it to badge table
CGI-OPEN-ENT-NG/minibadge pull request #16
Opened 2022-10-19 14:23 UTC by Rseuret

## Describe your changes
ajout d un table user pour récuperer le display name des users
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MBA-44
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-19 14:45 UTC, qpic-cgi requested changes

2022-10-19 14:45 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/Minibadge.java
> +        final EventBus eb = getEventBus(vertx);
y'a déjà une méthode pour ça dans le serviceFactory !

2022-10-19 14:45 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +        Set<String> distinctUsersIds = new HashSet<>(usersIds);
qu'est-ce que t'apport le hashSet à la place d'un List<String> ?

2022-10-19 14:45 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +            futures.add(upsertRequest(user));
tiens m'sieur RSer:
https://github.com/CGI-OPEN-ENT-NG/entcore/blob/dev/directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java#L553

Finalement il existe le fameux Bus dont te je parlais au début du ticket MBA-7 !
(va falloir qu'on se coordonne là dessus, car je suis entrain de l'implémenter pour mes besoins).

2022-10-19 14:45 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +            futures.add(upsertRequest(user));
je suis certains que tu peux nous faire tous ça en 2 requêtes max ;)

2022-10-19 14:45 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +                "  WHERE %s.id = EXCLUDED.id ;", USER_TABLE, USER_TABLE);
Alors avec mon commentaire au dessus, ça implique que tu le fasses avec des statments plutôt.

2022-10-20 07:47 UTC, Rseuret commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +        Set<String> distinctUsersIds = new HashSet<>(usersIds);
il permet d'éviter les doublons d'id

2022-10-20 08:41 UTC, Sofianebernoussi requested changes
Good avec les retours de qpic !

2022-10-20 13:21 UTC, qpic-cgi requested changes

2022-10-20 13:21 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +        return promise.future();
Comme je te disais dans mon commentaire plus tôt, je l'ai déjà implémenté:

```suggestion
@Override
    public Future<List<User>> getUsers(List<String> userIds) {
        Promise<List<User>> promise = Promise.promise();

        getUsersRequest(userIds)
                .onFailure(promise::fail)
                .onSuccess(users -> promise.complete(new User().toList(users)));

        return promise.future();
    }

    private Future<JsonArray> getUsersRequest(List<String> userIds) {
        Promise<JsonArray> promise = Promise.promise();

        JsonObject action = new JsonObject()
                .put(EventBusConst.ACTION, EventBusConst.LIST_USERS)
                .put(Field.USERIDS, userIds);

        eb.request(EventBusConst.DIRECTORY, action, PromiseHelper.messageHandler(promise, "")); //todo

        return promise.future();
    }
```

Fait attention, a bien distinguer tes besoins. Dans l'idéal, c'est une fonction, un besoin.

2022-10-21 08:59 UTC, qpic-cgi requested changes

2022-10-21 08:59 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/core/constants/EventBusConst.java
> +    public static final String USERIDS = "userIds";
Field

2022-10-21 08:59 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/helper/PromiseHelper.java
> +                promise.complete();
attention, ta promise est typée <R>, mais elle renvoie toujours une Promise<void>

2022-10-21 09:37 UTC, qpic-cgi requested changes

2022-10-21 09:37 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/helper/PromiseHelper.java
> +    public static <R> Handler<Message<JsonObject>> messageToPromise(Promise<Void> promise) {
R ne sert plus à rien du coup

2022-10-21 09:37 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
> +                sql.transaction(statements, PromiseHelper.messageToPromise(promise));
indent

2022-10-21 09:53 UTC, qpic-cgi requested changes

2022-10-21 09:53 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/helper/PromiseHelper.java
> +    public static <Void> Handler<Message<JsonObject>> messageToPromise(Promise<Void> promise) {
supprime < Void >

2022-10-21 09:59 UTC, qpic-cgi approved these changes

2022-10-21 11:47 UTC, merged