feat(BadgeType) #MBA-38: display target and assignor type
CGI-OPEN-ENT-NG/minibadge pull request #17
Opened 2022-10-24 08:28 UTC by Rseuret

## Describe your changes
display target and assignor type on badges
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MBA-38
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-24 08:34 UTC, qpic-cgi approved these changes

2022-10-24 08:34 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/id-type/id-type.html
> +                ng-bind="assigny "></span></div>
assigny ?

2022-10-25 14:21 UTC, qpic-cgi requested changes

2022-10-25 14:21 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-protagonist-setting.model.ts
> +        this.assignorType = data.assignorType;
Dans la logique des choses ici, ton data ne devrait être constitué seulement de différents éléments de réponses imbriqués:
IBadgeProtagonistSettingRelationResponse => IBadgeProtagonistSettingResponse.

du coup, il va falloir ici que tu instancie chaque morceau en un nouveau model, exemple:
```suggestion
        this.assignorType = new BadgeProtagonistSetting(<IBadgeProtagonistSettingResponse>data.assignorType)
```

2022-10-25 14:21 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-settings.model.ts
> +    is_self_assignable: boolean;
pourquoi du camel Case ici ?

2022-10-25 14:21 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    level?: string;
on parle toujours de level du coup ? et d'un tableau assignableBy ?

2022-10-25 14:21 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    settings?: BadgeSettings[];
Je comprend l'idée.
Malgré tout, ce qui va nous intéresser en front, c'est un setting ponctuel qui va concerner l'utilisateur (soit le setting par défaut, soit celui de sa structure). donc pas de tableau de setting ici.

2022-10-25 14:21 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-type.model.ts
> +        return assigners.toString()
En prenant en compte le fait qu'on ne récupère qu'un seul setting (com' plus haut):

```suggestion
        this.setting.relations.map((relation) => relation.assignorType.type).join(", ")
```

pareil pour receiver

2022-10-26 08:30 UTC, Rseuret commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    settings?: BadgeSettings[];
et quid des multi-étabs?

2022-10-26 08:37 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    settings?: BadgeSettings[];
Apriori, il prendrons les règles liés à leur étab principal.
De ce fait un seul setting à la fois.

2022-10-26 10:11 UTC, qpic-cgi requested changes

2022-10-26 10:11 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeSetting.java
> +                .put(Field.RELATIONS, relationsList)
relations.stream().map(reslation ->relation.toJson())..collect(Collectors.toList()

ça pourrais presque même faire l'objet d'une méthode dans model ou quelque chose comme ça ^^

2022-10-26 10:11 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeType.java
> +    private List<BadgeSetting> settings = new ArrayList<>();
Du coup, en se projetant dans le futur, tu crois qu'il serra intéressant de récupérer une liste de settings sur un badgeType ?
Perso je ne pense pas.

2022-10-26 10:11 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeType.java
> +        badgeType.put(Field.SETTINGS, settingsList);
settings.stream().map(setting->setting.toJson())..collect(Collectors.toList())

même remarque que pour le tableau de relations ^^

2022-10-26 10:11 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java
> +        badgeType.addSetting(badgeSetting);
CTRL + ALT + L

2022-10-26 12:23 UTC, Rseuret commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    settings?: BadgeSettings[];
donc il faut correspondre aussi le back ?

2022-10-26 12:27 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-type.model.ts
> +    settings?: BadgeSettings[];
ouaip, si tu regardes bien, ya un com' qui va avec !

2022-10-27 08:02 UTC, qpic-cgi requested changes

2022-10-27 08:02 UTC, qpic-cgi commented on src/main/resources/public/ts/models/badge-protagonist-setting.model.ts
> +    }
return new BadgeProtagonistSettingRelation().toList(protagonist);

2022-10-27 08:13 UTC, merged