feat(BadgeAssigned) #MBA-15: add revokation action
CGI-OPEN-ENT-NG/minibadge pull request #18
Opened 2022-10-24 13:06 UTC by Rseuret

## Describe your changes
add revokation action
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MBA-15
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-25 07:08 UTC, sjollois approved these changes

2022-10-25 07:08 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/BadgeAssignedController.java
> +    @ApiDoc("get all the badge the user has given")
ApiDoc pas correct

2022-10-25 15:31 UTC, qpic-cgi requested changes

2022-10-25 15:31 UTC, qpic-cgi commented on src/main/resources/public/ts/services/badges-given.service.ts
> +    },
CTRL + ALT + L

2022-10-27 08:19 UTC, qpic-cgi approved these changes

2022-10-27 08:23 UTC, merged