fix(Badge-Type) #MBA-59: now disable badge types when refused minibadge
CGI-OPEN-ENT-NG/minibadge pull request #27
Opened 2022-10-27 13:14 UTC by Rseuret

## Describe your changes
disable badge type if you didnt accept the chart
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MBA-59

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-27 13:15 UTC, qperie approved these changes

2022-10-27 13:22 UTC, sjollois approved these changes

2022-10-27 13:23 UTC, qpic-cgi requested changes

2022-10-27 13:23 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/badge-types.controller.ts
> +            || !!this.$scope.setting.userPermissions.acceptReceive;
c'est pas mieux si on en fait une méthode (ou property) dans userPermissions directement ?

2022-10-28 05:55 UTC, sjollois commented on src/main/resources/public/ts/controllers/badge-types.controller.ts
> +            || !!this.$scope.setting.userPermissions.acceptReceive;
à faire plus tard en ticket mais vraiment pas prio

2022-10-28 05:55 UTC, merged