feat(badge-type): #MBA-23 init detail badge type
CGI-OPEN-ENT-NG/minibadge pull request #4
Opened 2022-09-08 08:59 UTC by qpic-cgi

## Describe your changes
Initialisation de la vue du détail d'un type de badge

## Checklist tests
- Aller sur la collection de badges
- Cliquer sur un badge
- Admirer !
- tester le responsive

## Issue ticket number and link
[Jira - MBA-23](https://jira.support-ent.fr/browse/MBA-23)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-08 09:11 UTC, flmartineau commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java
> +                String.format("[Minibadge@%s::getBadgeTypes] Fail to retrieve badge types",
[Minibadge@%s::getBadgeType]

2022-09-09 15:44 UTC, sjollois commented on src/main/resources/public/ts/core/enum/date.enum.ts
> +    DAY_MONTH_YEAR_KEBAB = 'dd-MM-yyyy',
KEBAB ?

2022-09-09 16:22 UTC, qpic-cgi commented on src/main/resources/public/ts/core/enum/date.enum.ts
> +    DAY_MONTH_YEAR_KEBAB = 'dd-MM-yyyy',
kebab case

2022-09-09 16:25 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/User.java
> +public class User implements Model<User> {
UserInfo c'est vraiment le model qui va concerner l'utilisateur de la request.
Les props qu'on utilise pour ce model ne sont en plus pas forcement les mêmes (pas les mêmes méthodes non plus)

2022-09-09 16:26 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +
Pas possible ! Ce sont des URL params !

2022-09-09 16:29 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +    @ApiDoc("Retrieve badge type")
Yes, je ne l'ai pas rappelé pour cette PR, mais comme pour la précédente, dû a des délais serrés je ferais la sécurité et les TU ultérieurement.

2022-09-12 08:25 UTC, sjollois commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +    @ApiDoc("Retrieve badge type")
Pas de problème, mais on n'enverra pas en prod sans :)

2022-09-12 08:27 UTC, sjollois commented on src/main/resources/public/ts/core/enum/date.enum.ts
> +    DAY_MONTH_YEAR_KEBAB = 'dd-MM-yyyy',
je connaissais pas :)

2022-09-12 08:27 UTC, sjollois approved these changes

2022-09-12 08:28 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +    @ApiDoc("Retrieve badge type")
Cela va de soit ;p

2022-09-12 08:37 UTC, Rseuret commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +    @ApiDoc("Retrieve badge type")
il n y a pas de Sécurité sur l'API c est voulu?

2022-09-12 08:37 UTC, Rseuret commented on src/main/java/fr/cgi/minibadge/model/BadgeType.java
>          this.id = badgeType.getLong(Field.ID);
Que ce passe t'il si ton Json  passé en paramètre contient des données erronées?

2022-09-12 08:39 UTC, BastienBenard approved these changes

2022-09-12 08:39 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java
> +    @ApiDoc("Retrieve badge type")
Yes
[](https://github.com/CGI-OPEN-ENT-NG/minibadge/pull/4#discussion_r967259971)

2022-09-12 08:41 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeType.java
>          this.id = badgeType.getLong(Field.ID);
Cela revient à faire :
```
public BadgeType() {
}
```
il ne se passe donc rien

2022-09-12 08:51 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeType.java
>          this.id = badgeType.getLong(Field.ID);
Vue par teams => on va préférer utiliser les objects plutôt que les primitives ! je corriges ça rapidement !

2022-09-12 08:57 UTC, JinDouang requested changes

2022-09-12 08:57 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java
> +                        this.getClass().getSimpleName()))));
Est-ce qu'on pourrait l'externaliser dans une méthode dédiée pour la récupération ?

getBadgeTypeSQL par exemple ou un truc dans le genre

2022-09-12 08:57 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java
> +        badgeTypePromise.future()
Tu pourrais faire 

```
getBadgeTypeSQL
.compose
```

etc...

2022-09-12 08:57 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java
> +    public Future<BadgeType> getBadgeType(String structureId, long typeId, HttpServerRequest serverRequest) {
Je pense plutôt que lui passer un HttpServerRequest (très dédié côté controller), tu pourrais lui donner Renders.getHost(serverRequest) - String  et I18n.acceptLanguage(serverRequest) - String

Il faut qu'on évite les usages de HttpServerRequest parmis nos services/controller/cron etc à implémenter

2022-09-12 08:57 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultEventBusService.java
> +        eb.request(EventBusConst.VIESCOLAIRE, action, PromiseHelper.messageHandler(eventBusPromise,
Alors attention, les plateformes qui utilisent minibadge n'auront pas forcément viescolaire

A tester mais tu pourrais voir pour :  

```
  UserUtils.getUserInfos(eb, tonId, userInfos -> {
            
        });
    
```

2022-09-12 08:57 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultEventBusService.java
> +        eb.request(EventBusConst.VIESCOLAIRE, action, PromiseHelper.messageHandler(eventBusPromise,
Mais ça inciterait à utiliser UserInfo et non ton model User (à la limite ton model user pourrait l'étendre)

Sinon tu peux faire ta propre requête neo4j, à voir!

2022-09-12 08:57 UTC, JinDouang commented on src/main/resources/public/ts/services/badge-type.service.ts
> +        http.get(`/minibadge/structures/${structureId}/types/${typeId}`)
il manque pas le return ?

2022-09-12 08:58 UTC, qpic-cgi commented on src/main/resources/public/ts/services/badge-type.service.ts
> +        http.get(`/minibadge/structures/${structureId}/types/${typeId}`)
si, il y est

2022-09-12 09:08 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultEventBusService.java
> +        eb.request(EventBusConst.VIESCOLAIRE, action, PromiseHelper.messageHandler(eventBusPromise,
A rediscuter dans un ticket ultérieur,
Je créer le ticket de ce pas 
[Jira - MBA-29](https://jira.support-ent.fr/browse/MBA-29)

2022-09-12 09:09 UTC, JinDouang commented on src/main/resources/public/ts/services/badge-type.service.ts
> +        http.get(`/minibadge/structures/${structureId}/types/${typeId}`)
Ah oui j'avais pas vu mb!

2022-09-14 12:33 UTC, sjollois approved these changes

2022-09-14 13:18 UTC, BastienBenard approved these changes

2022-09-14 13:21 UTC, flmartineau approved these changes

2022-09-14 14:53 UTC, JinDouang approved these changes

2022-09-14 16:16 UTC, merged