feat(BadgeAssigned):MBA-7/Add Badge Assigned
CGI-OPEN-ENT-NG/minibadge pull request #8
Opened 2022-10-07 07:21 UTC by Rseuret

## Describe your changes
Ajout de l'écran des Badges Décernés 
## Checklist tests

## Issue ticket number and link

https://jira.support-ent.fr/browse/MBA-7

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-07 13:58 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeAssignedService.java
> +                    List<Future<Void>> futures = new ArrayList<>();
Ici tu pourrais découper ta méthode en plusieurs partie : 

* ta première instruction te permet de récupérer les badges
* ta deuxième instruction te permet de SETTER les user infos (et non un getOwnerid)
* ta troisième instruction consiste à filter les badges en fonction de ta query user

De ce fait, tu pourrais la découper comme ça : 

```
    @Override
    public Future<List<BadgeAssigned>> getBadgesGiven(EventBus eb, String query, String startDate, String endDate, String sortBy,
                                                      Boolean sortAsc, String assignorId) {
        Promise<List<BadgeAssigned>> promise = Promise.promise();
        getBadgesGivenRequest(assignorId, startDate, endDate, sortBy, sortAsc)
                .compose(badgesGiven -> setUserInfos(new BadgeAssigned().toList(badgesGiven)))
                .onSuccess(badgesGiven -> {
                    List<BadgeAssigned> finalBadgeAssignedList = badgesGiven;
                    if (query != null && !query.isEmpty())
                        finalBadgeAssignedList = badgesGiven.stream().filter(badgeAssigned ->
                                badgeAssigned.getBadge().owner().getFirstName().contains(query.toLowerCase())
                                        || badgeAssigned.getBadge().owner().getLastName().toLowerCase().contains(query.toLowerCase())
                                        || badgeAssigned.getBadge().getBadgeType().label().toLowerCase().contains(query.toLowerCase())).collect(Collectors.toList());

                    promise.complete(finalBadgeAssignedList);
                })
                .onFailure(promise::fail);

        return promise.future();
    }

// j'ai appelé setUserInfos au lieu de getOwnerId car dans la réalité tu fais un setUser
    Future<List<BadgeAssigned>> setUserInfos(EventBus eb, List<BadgeAssigned> badgeAssignedList) {
        Promise<List<BadgeAssigned>> promise = Promise.promise();
        Future<Void> current = Future.succeededFuture();
        for (int i = 0; i < badgeAssignedList.size(); i++) {
            int finalI = i;
            current = current.compose(v -> getOwnerId(eb, badgeAssignedList.get(finalI)));
        }
        current
                .onSuccess(res -> promise.complete(badgeAssignedList))
                .onFailure(promise::fail);
        return promise.future();
    }

```

2022-10-07 14:08 UTC, qpic-cgi commented on src/main/resources/public/sass/global/components/_given-array.scss
> +    color: white;
constant color

2022-10-07 14:09 UTC, qpic-cgi commented on src/main/resources/public/sass/global/components/_given-array.scss
> +    border-top: 1px solid lightgrey;
constant color

2022-10-07 14:20 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/badges-given.controller.ts
> +    subscriptions: Subscription = new Subscription();
pas utile

2022-10-07 14:23 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeAssignedService.java
> +                        " AND ba.created_at  <= to_date(?,'DD-MM-YYYY') " : "") +
to_date est nécessaire ici ? C'est pas plus intéressant de ce contenter du matching en front ?

2022-10-07 14:24 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-given-array/badge-given-array.ts
> +    label: string;
déclare ça dans tes interfaces !

2022-10-07 14:31 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/badge-given-array/badge-given-array.ts
> +            if (this.label === filterLabel)
SUGESTION: this.label === filterLabel ? this.isAsc = !this.isAsc : this.isAsc = true
ça prend moins de place et c'est joli

2022-10-07 14:32 UTC, qpic-cgi commented on src/main/resources/public/ts/services/badge-type.service.ts
> +    refuseBadgeType(typeId: number): Promise<AxiosPromise>;
attentions, ces 2 méthodes on étaient déplacés !
elles ne devraient pas être dans ta PR

2022-10-07 14:40 UTC, qpic-cgi commented on src/main/resources/public/ts/services/badges-given.service.ts
> +        http.get(`/minibadge/assigned/given${getParams(payload)}`)
Ici, je comprend la volonté de vouloir dissocié les 2,
Yes vraiment pas mal de logique dans sa méthode.
Du coup je n'ai pas vraiment d'avis là dessus

2022-10-11 07:52 UTC, JinDouang requested changes

2022-10-11 07:52 UTC, JinDouang commented on src/main/resources/public/sass/global/_mixins.scss
> +$minibadge-blue-dark
Tu n'as pas de valeur ici ?

2022-10-11 07:52 UTC, JinDouang commented on src/main/java/fr/cgi/minibadge/controller/BadgeAssignedController.java
> +    @ApiDoc("get all the badge the user has given")
la route API n'est pas sécurisé, à voir si c'est pris en compte pour le ticket actuel

2022-10-11 07:53 UTC, qpic-cgi requested changes

2022-10-11 07:53 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeAssignedService.java
> +                    List<BadgeAssigned> finalBadgeAssignedList = filterBadgesGiven(query, badgeAssignedList);
Après réflexion, tu pouvais filtrer par utilisateur au préalable !
1) tu récupère les userIds depuis tes badges souhaités
2) tu récupères tes users, tu récupère une liste de userIds filtré sur ton champ de recherche
3) tu récupères et filtres tes badges en fonction de ton champ de recherche OU présent dans ton tableau de userIds filtré

Hier tu m'expliquais le pb en me disant que si tu filtrais d'abord par displayName de user, y'aurais des correspondances que de label de badges que tu ne récupèrerais pas (ceux dont le user displayName ne correspondent pas).
Actuellement tu as le même problème dans le sens inverse, les user displayName qui correspondent au champ de recherche ne sont pas récupérés s'ils ne  correspondent pas au label de badges.

Avec ma solution, tu empêches ce problème.

2022-10-11 07:53 UTC, qpic-cgi commented on src/main/resources/public/sass/global/_mixins.scss
> +$minibadge-blue-dark
Pourquoi cette variable sans déclaration de couleur ?

2022-10-11 07:55 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/controller/BadgeAssignedController.java
> +    @ApiDoc("get all the badge the user has given")
la route devrait être merge avant, du coup ça devrait être pris en compte dans le ticket MBA-11 / MBA-12

2022-10-11 07:56 UTC, Rseuret commented on src/main/java/fr/cgi/minibadge/controller/BadgeAssignedController.java
> +    @ApiDoc("get all the badge the user has given")
De mémoire il me semble que la sécurité des API se fera plus tard

2022-10-21 14:25 UTC, qpic-cgi requested changes

2022-10-22 09:16 UTC, qpic-cgi requested changes

2022-10-22 09:16 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/id-type/id-type.html
> +            <i18n>minibadge.created.by</i18n>&Tab;<span>[[vm.badgeType.owner.displayName]]</span></div>
```suggestion
            <i18n>minibadge.created.by</i18n>&Tab;<span>[[vm.badgeType.owner.getDisplayName()]]</span></div>
```

2022-10-22 09:18 UTC, qpic-cgi requested changes

2022-10-22 09:18 UTC, qpic-cgi commented on src/main/resources/sql/010-badges-add-display-name.sql
> +CREATE TABLE minibadge.user (
Attention ! 010-... existe déjà désormais !

2022-10-24 08:55 UTC, Rseuret commented on src/main/java/fr/cgi/minibadge/core/constants/EventBusConst.java
> +    public static final String LIST_USERS =  "list-users";
si j'ai rebase depuis mba-44

2022-10-24 09:11 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/core/constants/EventBusConst.java
> +    public static final String LIST_USERS =  "list-users";
tu dois rebase depuis dev, et non depuis MBA-44

2022-10-24 12:08 UTC, qpic-cgi requested changes

2022-10-24 12:08 UTC, qpic-cgi commented on src/main/java/fr/cgi/minibadge/model/BadgeAssigned.java
> +                .put(Field.DISPLAYNAME,display_name)
display_name => displayName (nos variable en java sont plutôt en camelCase, soucis d'uniformité ^^)

2022-10-24 12:15 UTC, qpic-cgi approved these changes

2022-10-24 12:16 UTC, merged